# Generated by Django 4.2.27 on 2025-12-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gap",
            name="severity",
            field=models.CharField(default="low", max_length=50),
        ),
        migrations.AlterField(
            model_name="gap",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
