# Generated by Django 4.2.27 on 2025-12-07 22:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_gap_severity_alter_gap_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="gap",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
