# Generated by Django 4.2.27 on 2025-12-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_gap_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="gap",
            name="recommendations",
            field=models.TextField(blank=True, default="None", null=True),
        ),
    ]
