# Generated by Django 4.2.27 on 2025-12-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_gap_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='gap',
            name='actual_completion',
            field=models.DateField(blank=True, help_text='Actual completion date', null=True),
        ),
        migrations.AddField(
            model_name='gap',
            name='budget_allocated',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budget allocated in INR', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='gap',
            name='budget_spent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Budget spent in INR', max_digits=12),
        ),
        migrations.AddField(
            model_name='gap',
            name='expected_completion',
            field=models.DateField(blank=True, help_text='Expected completion date', null=True),
        ),
        migrations.AddField(
            model_name='gap',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='gap',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='gap',
            name='start_date',
            field=models.DateField(blank=True, help_text='Project start date', null=True),
        ),
    ]
