# Generated by Django 4.2.27 on 2025-12-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_gap_actual_completion_gap_budget_allocated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(max_length=20, unique=True)),
                ('villager_name', models.CharField(max_length=100)),
                ('complaint_text', models.TextField(help_text='Original complaint text')),
                ('complaint_type', models.CharField(blank=True, max_length=100)),
                ('priority_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('received_post', 'Received at Post Office'), ('sent_to_office', 'Sent to PM-AJAY Office'), ('under_analysis', 'AI Analysis in Progress'), ('assigned_worker', 'Assigned to Field Worker'), ('work_in_progress', 'Work in Progress'), ('work_completed', 'Work Reported Complete'), ('sent_to_villager', 'Report Sent to Villager'), ('villager_satisfied', 'Villager Confirmed Satisfied'), ('villager_unsatisfied', 'Villager Reported Unsatisfied'), ('case_closed', 'Case Closed'), ('escalated', 'Escalated to Higher Authority')], default='received_post', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='complaint_audio/')),
                ('audio_transcription', models.TextField(blank=True, help_text='AI transcription of audio')),
                ('recorded_by_agent', models.BooleanField(default=False)),
                ('agent_name', models.CharField(blank=True, max_length=100)),
                ('villager_signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geotagged_photos', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='PMAJAYOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('officer_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=6)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postmaster_name', models.CharField(blank=True, max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('assigned_post_offices', models.ManyToManyField(to='core.postoffice')),
                ('assigned_villages', models.ManyToManyField(to='core.village')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('action_by', models.CharField(max_length=100)),
                ('action_type', models.CharField(choices=[('received', 'Document Received'), ('scanned', 'Document Scanned'), ('ai_analysis', 'AI Analysis Complete'), ('assigned', 'Assigned to Worker'), ('work_update', 'Work Progress Update'), ('report_sent', 'Report Sent'), ('feedback_received', 'Villager Feedback'), ('case_closed', 'Case Closed'), ('escalated', 'Case Escalated')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='core.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('worker_type', models.CharField(help_text='Electrician, Plumber, etc.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('village_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.village')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('worker_type', models.CharField(choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('road_contractor', 'Road Contractor'), ('mason', 'Mason'), ('healthcare', 'Healthcare Worker'), ('agriculture', 'Agriculture Specialist'), ('general', 'General Worker')], max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_available', models.BooleanField(default=True)),
                ('current_location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pmajay_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pmajayoffice')),
            ],
        ),
        migrations.CreateModel(
            name='VillagerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('villager_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('complaint_number', models.CharField(max_length=10, unique=True)),
                ('last_sms_sent', models.DateTimeField(blank=True, null=True)),
                ('villager_satisfied', models.BooleanField(default=False)),
                ('case_closed', models.BooleanField(default=False)),
                ('gap', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.gap')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('follow_ups_completed', models.JSONField(default=list)),
                ('photos_collected', models.JSONField(default=list)),
                ('signatures_collected', models.JSONField(default=list)),
                ('new_complaints_filed', models.IntegerField(default=0)),
                ('audio_recordings', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.surveyagent')),
                ('complaints_collected', models.ManyToManyField(blank=True, to='core.complaint')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.village')),
            ],
        ),
        migrations.CreateModel(
            name='SMSStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_phone', models.CharField(help_text='Phone number that sent SMS', max_length=15)),
                ('sms_command', models.CharField(choices=[('START', 'Work Started'), ('PROGRESS', 'Work in Progress'), ('DONE', 'Work Completed'), ('PROBLEM', 'Issue/Delay'), ('CHECKED', 'Villager Checked Work'), ('SATISFIED', 'Villager Satisfied'), ('UNSATISFIED', 'Villager Not Satisfied')], max_length=20)),
                ('raw_sms_text', models.TextField(help_text='Original SMS received')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_sent', models.TextField(blank=True, null=True)),
                ('response_sent_at', models.DateTimeField(blank=True, null=True)),
                ('gap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_updates', to='core.gap')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleWorkflowTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('complaint_received', 'Complaint Received'), ('sent_to_pm_ajay', 'Sent to PM-AJAY Office'), ('worker_assigned', 'Worker Assigned'), ('work_started', 'Work Started'), ('work_in_progress', 'Work in Progress'), ('work_completed', 'Work Completed'), ('sent_to_villager', 'Report Sent to Villager'), ('villager_satisfied', 'Villager Satisfied'), ('villager_unsatisfied', 'Villager Not Satisfied - Reopened'), ('case_closed', 'Case Closed')], default='complaint_received', max_length=30)),
                ('stage_updated_at', models.DateTimeField(auto_now=True)),
                ('total_sms_sent', models.IntegerField(default=0)),
                ('last_sms_to_villager', models.DateTimeField(blank=True, null=True)),
                ('last_sms_to_worker', models.DateTimeField(blank=True, null=True)),
                ('assigned_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workercontact')),
                ('gap', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.gap')),
                ('villager_contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.villagercontact')),
            ],
        ),
        migrations.AddField(
            model_name='pmajayoffice',
            name='serves_post_offices',
            field=models.ManyToManyField(blank=True, to='core.postoffice'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='pmajay_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pmajayoffice'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='post_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.postoffice'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.village'),
        ),
    ]
