# Generated by Django 4.2.27 on 2025-12-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_complaint_pmajayoffice_postoffice_surveyagent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gap',
            name='input_method',
            field=models.CharField(choices=[('text', 'Text/Image'), ('voice', 'Voice/Audio')], default='text', help_text='Method used to submit this gap', max_length=10),
        ),
    ]
