# Generated by Django 4.2.27 on 2025-12-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_gap_input_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gap',
            name='input_method',
            field=models.CharField(choices=[('image', 'Image Upload'), ('voice', 'Voice Recording'), ('text', 'Text Input')], default='image', help_text='Method used to submit this gap', max_length=10),
        ),
    ]
