# Generated by Django 4.2.27 on 2025-12-08 17:44

from django.db import migrations


def update_input_methods(apps, schema_editor):
    Gap = apps.get_model('core', 'Gap')
    # Update all existing records with "text" to "image" since they were likely image uploads
    Gap.objects.filter(input_method='text').update(input_method='image')


def reverse_update_input_methods(apps, schema_editor):
    Gap = apps.get_model('core', 'Gap')
    # Reverse the operation
    Gap.objects.filter(input_method='image').update(input_method='text')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_gap_input_method'),
    ]

    operations = [
        migrations.RunPython(update_input_methods, reverse_update_input_methods),
    ]
