# Generated by Django 4.2.27 on 2025-12-09 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20251208_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_audio_path', models.CharField(help_text='Path to verification audio file', max_length=500)),
                ('similarity_score', models.FloatField(help_text='Voice similarity score (0.0 to 1.0)')),
                ('is_match', models.BooleanField(default=False, help_text='Whether voices matched')),
                ('confidence', models.CharField(choices=[('high', 'High - 90%+ match'), ('medium', 'Medium - 85-90% match'), ('low', 'Low - 75-85% match'), ('very_low', 'Very Low - Below 75%'), ('error', 'Verification Error')], max_length=20)),
                ('verification_date', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.CharField(blank=True, help_text='Person who attempted verification', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('used_for_closure', models.BooleanField(default=False)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_verifications', to='core.complaint')),
            ],
            options={
                'verbose_name': 'Voice Verification Log',
                'verbose_name_plural': 'Voice Verification Logs',
                'ordering': ['-verification_date'],
            },
        ),
    ]
