# Generated by Django 4.2.27 on 2025-12-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_voiceverificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='gap',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Audio file if submitted via voice', null=True, upload_to='gap_audio/'),
        ),
    ]
