# Generated by Django 4.2.27 on 2025-12-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_gap_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='voice_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique voice fingerprint for complaint audio', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='gap',
            name='voice_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique voice fingerprint for voice-based gaps', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='voiceverificationlog',
            name='verification_voice_code',
            field=models.CharField(blank=True, help_text='Voice code of verification audio', max_length=64, null=True),
        ),
    ]
