# Generated by Django 4.2.27 on 2025-12-09 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_complaint_voice_code_gap_voice_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceverificationlog',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_verifications', to='core.complaint'),
        ),
    ]
