# Generated by Django 4.2.27 on 2025-12-09 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_alter_voiceverificationlog_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ground', 'Ground Level'), ('manager', 'Manager'), ('authority', 'Highest Authority'), ('admin', 'Admin')], default='ground', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QRSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_code', models.TextField(help_text='Raw QR code data scanned')),
                ('person_name', models.CharField(max_length=200)),
                ('person_photo', models.ImageField(blank=True, help_text='Photo of the person submitting', null=True, upload_to='qr_submissions/photos/')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('village_name', models.CharField(help_text='Village name from mobile app', max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('form_type', models.CharField(default='complaint', max_length=50)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_from_mobile', models.BooleanField(default=True, help_text='True if synced from mobile app')),
                ('mobile_created_at', models.DateTimeField(blank=True, help_text='Original creation time on mobile', null=True)),
                ('linked_complaint', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_submission', to='core.complaint')),
                ('linked_gap', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_submission', to='core.gap')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.village')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRComplaintDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_text', models.TextField()),
                ('complaint_type', models.CharField(blank=True, max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('additional_photos', models.JSONField(default=list, help_text='List of additional photo file paths')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='qr_submissions/audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_from_mobile', models.BooleanField(default=True)),
                ('qr_submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_details', to='core.qrsubmission')),
            ],
        ),
    ]
