# Generated by Django 4.2.27 on 2025-12-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_userprofile_qrsubmission_qrcomplaintdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="gap",
            name="authority_flagged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gap",
            name="manager_flagged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
