# Generated by Django 4.2.27 on 2025-12-17 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_gap_flag_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gap',
            name='authority_flagged_at',
        ),
        migrations.RemoveField(
            model_name='gap',
            name='manager_flagged_at',
        ),
    ]
