# Generated by Django 4.2.27 on 2025-12-17 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_gap_authority_flagged_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceverificationlog',
            name='gap',
            field=models.ForeignKey(blank=True, help_text='Gap being verified', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_verifications', to='core.gap'),
        ),
    ]
