# Generated by Django 4.2.27 on 2026-01-08 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_voiceverificationlog_gap'),
    ]

    operations = [
        migrations.AddField(
            model_name='gap',
            name='resolution_proof',
            field=models.FileField(blank=True, help_text='Document/letter proving gap resolution (required for AUTHORITY to close)', null=True, upload_to='resolution_proofs/'),
        ),
        migrations.AddField(
            model_name='gap',
            name='resolution_proof_number',
            field=models.CharField(blank=True, help_text='Reference number of resolution letter/document', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gap',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when gap was resolved', null=True),
        ),
        migrations.AddField(
            model_name='gap',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='User who marked this as resolved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_gaps', to=settings.AUTH_USER_MODEL),
        ),
    ]
