# Generated by Django 4.2.27 on 2026-02-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_resolution_proof_and_role_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gap',
            name='budget_allocated',
        ),
        migrations.RemoveField(
            model_name='gap',
            name='budget_spent',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('received_post', 'Received at Post Office'), ('sent_to_office', 'Sent to PM-AJAY Office'), ('under_analysis', 'AI Analysis in Progress'), ('assigned_worker', 'Assigned to Field Worker'), ('work_in_progress', 'Work in Progress'), ('work_completed', 'Work Reported Complete'), ('sent_to_villager', 'Report Sent to Villager'), ('villager_satisfied', 'Villager Confirmed Satisfied'), ('villager_unsatisfied', 'Villager Reported Unsatisfied'), ('case_closed', 'Case Closed'), ('escalated', 'Escalated to Admin')], default='received_post', max_length=30),
        ),
        migrations.AlterField(
            model_name='gap',
            name='resolution_proof',
            field=models.FileField(blank=True, help_text='Document/letter proving gap resolution (required for ADMIN to close)', null=True, upload_to='resolution_proofs/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ground', 'Ground Level'), ('manager', 'Manager'), ('admin', 'Admin')], default='ground', max_length=20),
        ),
    ]
