# Generated by Django 4.2.27 on 2026-02-10 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_budget_and_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='post_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.postoffice'),
        ),
        migrations.AlterField(
            model_name='workflowlog',
            name='action_type',
            field=models.CharField(choices=[('received', 'Document Received'), ('scanned', 'Document Scanned'), ('ai_analysis', 'AI Analysis Complete'), ('assigned', 'Assigned to Worker'), ('work_update', 'Work Progress Update'), ('report_sent', 'Report Sent'), ('feedback_received', 'Villager Feedback'), ('case_closed', 'Case Closed'), ('escalated', 'Case Escalated'), ('status_update', 'Status Update'), ('sms_update', 'SMS Update')], max_length=50),
        ),
    ]
