# Generated by Django 4.2.27 on 2026-02-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_fix_complaint_post_office_nullable_and_workflow_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsstatusupdate',
            name='gap',
        ),
        migrations.RemoveField(
            model_name='villagercontact',
            name='gap',
        ),
        migrations.RemoveField(
            model_name='workercontact',
            name='village_area',
        ),
        migrations.DeleteModel(
            name='SimpleWorkflowTracker',
        ),
        migrations.DeleteModel(
            name='SMSStatusUpdate',
        ),
        migrations.DeleteModel(
            name='VillagerContact',
        ),
        migrations.DeleteModel(
            name='WorkerContact',
        ),
    ]
