# Generated by Django 4.2.27 on 2026-03-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_dead_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gap',
            name='gap_type',
            field=models.CharField(choices=[('road', 'Road Infrastructure'), ('water', 'Water Supply'), ('electricity', 'Electricity'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('sanitation', 'Sanitation'), ('housing', 'Housing'), ('agriculture', 'Agriculture'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='gap',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=50),
        ),
    ]
