# Generated by Django 4.2.27 on 2026-03-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_gap_gap_type_alter_gap_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gap',
            name='gap_type',
            field=models.CharField(choices=[('water', 'Water Supply'), ('road', 'Road Infrastructure'), ('sanitation', 'Sanitation'), ('electricity', 'Electricity'), ('education', 'Education'), ('health', 'Healthcare'), ('housing', 'Housing'), ('agriculture', 'Agriculture'), ('connectivity', 'Connectivity'), ('employment', 'Employment'), ('community_center', 'Community Center'), ('drainage', 'Drainage'), ('other', 'Other')], max_length=100),
        ),
    ]
