# Generated by Django 4.2.27 on 2026-03-12 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0023_sync_gap_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gap',
            name='gap_type',
            field=models.CharField(choices=[('water', 'Water Supply'), ('road', 'Road Infrastructure'), ('sanitation', 'Sanitation'), ('electricity', 'Electricity'), ('education', 'Education'), ('health', 'Healthcare'), ('housing', 'Housing'), ('agriculture', 'Agriculture'), ('connectivity', 'Connectivity'), ('employment', 'Employment'), ('community_center', 'Community Center'), ('drainage', 'Drainage'), ('other', 'Other')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gap',
            name='input_method',
            field=models.CharField(choices=[('image', 'Image Upload'), ('voice', 'Voice Recording'), ('text', 'Text Input')], db_index=True, default='image', help_text='Method used to submit this gap', max_length=10),
        ),
        migrations.AlterField(
            model_name='gap',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='low', max_length=50),
        ),
        migrations.AlterField(
            model_name='gap',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='GapStatusAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, help_text='Previous status (null for newly created gaps)', max_length=20, null=True)),
                ('new_status', models.CharField(help_text='New status after the change', max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the status change')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the status change')),
                ('source', models.CharField(default='web', help_text='Source of the change (web, mobile, api, etc.)', max_length=50)),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gap_status_changes', to=settings.AUTH_USER_MODEL)),
                ('gap', models.ForeignKey(help_text='The gap whose status changed', on_delete=django.db.models.deletion.CASCADE, related_name='status_audit_logs', to='core.gap')),
            ],
            options={
                'verbose_name': 'Gap Status Audit Log',
                'verbose_name_plural': 'Gap Status Audit Logs',
                'ordering': ['-changed_at'],
            },
        ),
    ]
