# Generated by Django 4.2.27 on 2026-03-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_gap_status_audit_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gap',
            name='voice_code',
            field=models.CharField(blank=True, help_text='Unique voice fingerprint for voice-based gaps', max_length=64, null=True, unique=True),
        ),
    ]
