# Generated by Django 4.2.27 on 2026-04-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_fix_voice_code_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='gap',
            name='audio_url',
            field=models.URLField(blank=True, help_text='External audio URL (Cloudinary) - will be downloaded to audio_file', max_length=500, null=True),
        ),
    ]
