# Generated by Django 4.2.27 on 2026-04-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_add_complaint_photo_geo_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gap',
            name='closure_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude where the closure photo was taken', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='gap',
            name='closure_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude where the closure photo was taken', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='gap',
            name='closure_photo_timestamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the closure photo was captured on-site', null=True),
        ),
    ]
