"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    # Generate a secure random key for development if not set
    import secrets
    SECRET_KEY = secrets.token_urlsafe(50)
    print("⚠️  WARNING: SECRET_KEY not set. Generated a temporary one for development.")

# SECURITY WARNING: don't run with debug turned on in production!
# Default to False for safer behavior when env vars are missing.
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
RAILWAY_PUBLIC_DOMAIN = os.getenv("RAILWAY_PUBLIC_DOMAIN")
if RAILWAY_PUBLIC_DOMAIN:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)
if DEBUG:
    ALLOWED_HOSTS = ["*"]  # Allow all hosts in development only

CSRF_TRUSTED_ORIGINS = []
if RAILWAY_PUBLIC_DOMAIN:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RAILWAY_PUBLIC_DOMAIN}")

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Production security settings
if not DEBUG:
    # HTTPS/SSL settings
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS settings (only enable after testing HTTPS works)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Additional security headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = "DENY"


# Application definition

INSTALLED_APPS = [
    "unfold",  # Must be before django.contrib.admin
    "unfold.contrib.filters",  # Enhanced admin filters
    "unfold.contrib.forms",  # Enhanced admin forms
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "core",
]

# Django Unfold Admin Configuration
UNFOLD = {
    "SITE_TITLE": "SETU Admin",
    "SITE_HEADER": "SETU Administration",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: "/static/images/light-mode.png",
        "dark": lambda request: "/static/images/dark-mode.png",
    },
    "SITE_SYMBOL": "monitoring",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "config.settings.environment_callback",
    "DASHBOARD_CALLBACK": "core.admin_dashboard.dashboard_callback",
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "168 85 247",
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
            "950": "59 7 100",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Dashboard",
                "separator": True,
                "items": [
                    {
                        "title": "Home",
                        "icon": "home",
                        "link": "/",
                    },
                    {
                        "title": "Admin Dashboard",
                        "icon": "dashboard",
                        "link": "/admin/",
                    },
                ],
            },
            {
                "title": "Village Management",
                "separator": True,
                "items": [
                    {
                        "title": "Villages",
                        "icon": "location_city",
                        "link": "/admin/core/village/",
                    },
                    {
                        "title": "Gaps",
                        "icon": "report_problem",
                        "link": "/admin/core/gap/",
                        "badge": "core.admin_dashboard.gap_badge_callback",
                    },
                    {
                        "title": "Gap Audit Logs",
                        "icon": "history",
                        "link": "/admin/core/gapstatusauditlog/",
                    },
                ],
            },
            {
                "title": "Complaints & Workflow",
                "separator": True,
                "items": [
                    {
                        "title": "Complaints",
                        "icon": "feedback",
                        "link": "/admin/core/complaint/",
                        "badge": "core.admin_dashboard.complaint_badge_callback",
                    },
                    {
                        "title": "Workflow Logs",
                        "icon": "receipt_long",
                        "link": "/admin/core/workflowlog/",
                    },
                ],
            },
            {
                "title": "Offices & Personnel",
                "separator": True,
                "items": [
                    {
                        "title": "Post Offices",
                        "icon": "mail",
                        "link": "/admin/core/postoffice/",
                    },
                    {
                        "title": "PMAJAY Offices",
                        "icon": "business",
                        "link": "/admin/core/pmajayoffice/",
                    },
                    {
                        "title": "Survey Agents",
                        "icon": "person_search",
                        "link": "/admin/core/surveyagent/",
                    },
                    {
                        "title": "Workers",
                        "icon": "engineering",
                        "link": "/admin/core/worker/",
                    },
                ],
            },
            {
                "title": "Survey & QR",
                "separator": True,
                "items": [
                    {
                        "title": "Survey Visits",
                        "icon": "event_note",
                        "link": "/admin/core/surveyvisit/",
                    },
                    {
                        "title": "QR Submissions",
                        "icon": "qr_code_scanner",
                        "link": "/admin/core/qrsubmission/",
                    },
                    {
                        "title": "QR Complaint Details",
                        "icon": "description",
                        "link": "/admin/core/qrcomplaintdetail/",
                    },
                ],
            },
            {
                "title": "User Management",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "people",
                        "link": "/admin/auth/user/",
                    },
                    {
                        "title": "User Profiles",
                        "icon": "badge",
                        "link": "/admin/core/userprofile/",
                    },
                    {
                        "title": "Groups",
                        "icon": "groups",
                        "link": "/admin/auth/group/",
                    },
                ],
            },
        ],
    },
    "TABS": [
        {
            "models": ["core.gap"],
            "items": [
                {
                    "title": "All Gaps",
                    "link": "/admin/core/gap/",
                },
                {
                    "title": "Pending",
                    "link": "/admin/core/gap/?status__exact=pending",
                },
                {
                    "title": "In Progress",
                    "link": "/admin/core/gap/?status__exact=in_progress",
                },
                {
                    "title": "Resolved",
                    "link": "/admin/core/gap/?status__exact=resolved",
                },
            ],
        },
        {
            "models": ["core.complaint"],
            "items": [
                {
                    "title": "All Complaints",
                    "link": "/admin/core/complaint/",
                },
                {
                    "title": "Open",
                    "link": "/admin/core/complaint/?status__exact=open",
                },
                {
                    "title": "In Progress",
                    "link": "/admin/core/complaint/?status__exact=in_progress",
                },
                {
                    "title": "Resolved",
                    "link": "/admin/core/complaint/?status__exact=resolved",
                },
            ],
        },
    ],
}


def environment_callback(request):
    """Return environment info for admin header"""
    import os

    if os.getenv("RAILWAY_PUBLIC_DOMAIN"):
        return ["Production", "success"]
    elif os.getenv("DEBUG", "False").lower() == "true":
        return ["Development", "warning"]
    return ["Staging", "info"]


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
# Redirect users based on role (see core.views.post_login_redirect)
LOGIN_REDIRECT_URL = "/post-login/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# Email configuration (defaults to Gmail SMTP; override via .env)
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() == "true"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False").lower() == "true"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@example.com")
SMS_WEBHOOK_SECRET = os.getenv("SMS_WEBHOOK_SECRET", "")

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "logs", "django.log"),
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "core": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Create logs directory if it doesn't exist
logs_dir = BASE_DIR / "logs"
logs_dir.mkdir(exist_ok=True)

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "logs", "django.log"),
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "core": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Create logs directory if it doesn't exist
logs_dir = BASE_DIR / "logs"
logs_dir.mkdir(exist_ok=True)


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Supports PostgreSQL in production via env vars; falls back to SQLite for development
DATABASE_URL = os.getenv("DATABASE_URL", "")

if DATABASE_URL:
    # Production: PostgreSQL via DATABASE_URL
    # Format: postgres://USER:PASSWORD@HOST:PORT/DBNAME
    import dj_database_url

    DATABASES = {"default": dj_database_url.parse(DATABASE_URL, conn_max_age=600)}
else:
    # Development: SQLite (zero setup)
    DB_ENGINE = os.getenv("DB_ENGINE", "django.db.backends.sqlite3")
    if DB_ENGINE == "django.db.backends.sqlite3":
        DATABASES = {
            "default": {
                "ENGINE": DB_ENGINE,
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }
    else:
        # Manual PostgreSQL config without DATABASE_URL
        DATABASES = {
            "default": {
                "ENGINE": DB_ENGINE,
                "NAME": os.getenv("DB_NAME", "setu_db"),
                "USER": os.getenv("DB_USER", "postgres"),
                "PASSWORD": os.getenv("DB_PASSWORD", ""),
                "HOST": os.getenv("DB_HOST", "localhost"),
                "PORT": os.getenv("DB_PORT", "5432"),
            }
        }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization with correct timezone
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

LANGUAGES = [
    ("en", "English"),
    ("hi", "Hindi"),
]

TIME_ZONE = "Asia/Kolkata"  # Indian Standard Time instead of UTC

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [BASE_DIR / "locale"]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "core" / "static"]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS settings for mobile app
CORS_ALLOWED_ORIGINS = [
    "http://192.168.1.100:8000",
]
if RAILWAY_PUBLIC_DOMAIN:
    CORS_ALLOWED_ORIGINS.append(f"https://{RAILWAY_PUBLIC_DOMAIN}")

CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only allow all origins in development

# REST Framework settings with security improvements
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,  # Reduced from 20 to 50 for better performance
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
    },
}
